<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CodeLab.Service.Mail-415bcc5f-1302-45bf-bc6a-5c0cc4dbbfde</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeLab.Infrastructure.RabbitMq/CodeLab.Infrastructure.RabbitMq.csproj" />
  </ItemGroup>
</Project>
