<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeLab.Domain/CodeLab.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Http/" />
    <Folder Include="Http/Interfaces/" />
    <Folder Include="Microsoft/Auth/DTOs/" />
    <Folder Include="Telegram/Enums/" />
    <Folder Include="Telegram/Interfaces/" />
  </ItemGroup>

</Project>
